-- 실무에서 비트 연산자 사용 경험 없음..해답 참고
SELECT
    C.ID,
    C.GENOTYPE,
    P.GENOTYPE PARENT_GENOTYPE
FROM
    ECOLI_DATA C
    INNER JOIN ECOLI_DATA P ON C.PARENT_ID = P.ID
WHERE
    C.GENOTYPE & P.GENOTYPE = P.GENOTYPE
ORDER BY
    C.ID